name: java-docker-build

on:
  workflow_dispatch:

  push:
    branches: [main, feat/*]

jobs:
  java-maven:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
